title : Alec Gorge's Blog
tagline: 'Musing on iOS development, music, PHP, Ruby, node.js and everything inbetween.'
author :
  name : Alec Gorge
  email : alecgorge@gmail.com
  github : alecgorge
  twitter : alecgorge
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
